import type { ImportedRoundPatient } from "../types/round";

export function mockImportedPatients(): ImportedRoundPatient[] {
  return [
    { id: "L01", leito: "L01", nome: "MARIA DE LOURDES DA SILVA FERREIRA", idade: "88", sexo: "F", diagnosticos: "PAC, HDA ESTABILIZADA", comorbidades: "HAS, DM2, SEQUELA DE AVC", dispositivos: "JELCO MSD, SVD", antibioticos: "MEROPENEM 1G EV 8/8H - D5/10", laboratorio: "HB 9,2 / HT 28 / LEUCO 14.400 / CR 1,8 / PCR 42", quadro: "GRAVE ESTADO GERAL, CLINICAMENTE INSTÁVEL, EUPNEICA EM AR AMBIENTE.", intercorrencias: "MOVIMENTOS REPETITIVOS EM HEMIFACE ESQUERDA.", pendencias: "FONOAUDIOLOGIA E EXTRAÇÃO DENTÁRIA.", alertas: ["RISCO DE ASPIRAÇÃO", "ALERTA RENAL"] },
    { id: "L02", leito: "L02", nome: "VANUZIA PEREIRA DE SOUZA SILVA", idade: "55", sexo: "F", diagnosticos: "PAC", comorbidades: "ROUQUIDÃO CRÔNICA, COLAPSO T12", dispositivos: "JELCO MSE", antibioticos: "CEFTRIAXONA D7/10 + AZITROMICINA D5/5", laboratorio: "PCR 28", quadro: "BEG, ESTÁVEL, EUPNEICA EM AR AMBIENTE.", intercorrencias: "SEM INTERCORRÊNCIAS.", pendencias: "RNM DE TÓRAX COM CONTRASTE.", alertas: ["ATB FINALIZANDO"] },
    { id: "L03", leito: "L03", nome: "DIANA RIBEIRO", idade: "41", sexo: "F", diagnosticos: "ERISIPELA BOLHOSA MID, PÉ DIABÉTICO", comorbidades: "ESQUIZOFRENIA, DM, OBESIDADE", dispositivos: "JELCO MSE", antibioticos: "PIPERACILINA-TAZOBACTAM D1/10", laboratorio: "LEUCO 18.200 / PCR 33", quadro: "REG, ESTÁVEL, FERIDA COM SINAIS FLOGÍSTICOS.", intercorrencias: "DEBRIDAMENTO CIRÚRGICO EM 08/04.", pendencias: "PARECER DA PSIQUIATRIA PARA ALTA.", alertas: ["FERIDA INFECTADA", "FALHA TERAPÊUTICA"] },
    { id: "L04", leito: "L04", nome: "TERESINHA CAMPOS NUNES", idade: "80", sexo: "F", diagnosticos: "DAOP CRÍTICA, ITU", comorbidades: "PÉ DIABÉTICO, HAS, DM2", dispositivos: "JELCO MSE", antibioticos: "CIPROFLOXACINO D2/7", laboratorio: "CR 1,1 / PCR 12", quadro: "REG, ESTÁVEL, DELIRIUM NOTURNO.", intercorrencias: "SEM INTERCORRÊNCIAS.", pendencias: "REGULAÇÃO JUDICIAL PARA ANGIOPLASTIA DE MID.", alertas: ["DELIRIUM", "AGUARDA REGULAÇÃO"] },
    { id: "L05", leito: "L05", nome: "MARINA ROSA DE JESUS", idade: "86", sexo: "F", diagnosticos: "DM DESCOMPENSADA, PAC", comorbidades: "HAS, ALZHEIMER", dispositivos: "JELCO MD, SNE EM PAUSA", antibioticos: "CEFTRIAXONA D5/7", laboratorio: "HB 8,5 / HT 24 / VCM 112 / PCR 85", quadro: "REG, EUPNEICA EM AR AMBIENTE. VÔMITOS APÓS DIETA.", intercorrencias: "VÔMITOS.", pendencias: "RNM ENCÉFALO E ENDOCRINOLOGIA.", alertas: ["ANEMIA SEVERA", "RISCO DE ASPIRAÇÃO"] },
    { id: "L06", leito: "L06", nome: "EDITE SOARES DE SOUZA", idade: "78", sexo: "F", diagnosticos: "DRC AGUDIZADA, ITU", comorbidades: "ALZHEIMER, HAS, DM2", dispositivos: "JELCO MSE", antibioticos: "TAZOCIN D14/14", laboratorio: "CR 1,6 / UR 88 / K 5,2 / PCR 8", quadro: "REG, ESTÁVEL, DESORIENTAÇÃO BASAL.", intercorrencias: "SEM INTERCORRÊNCIAS.", pendencias: "RELATÓRIO PARA NEFROLOGIA.", alertas: ["ALERTA RENAL", "ATB FINALIZANDO"] },
    { id: "L07", leito: "L07", nome: "MARIA APARECIDA FEITOSA SANTOS", idade: "75", sexo: "F", diagnosticos: "PAC REFRATÁRIA", comorbidades: "DM2, HAS, HIPOTIREOIDISMO", dispositivos: "JELCO MSD", antibioticos: "LEVOFLOXACINO D7/10", laboratorio: "LEUCO 11.800 / PCR 18", quadro: "REG, ESTÁVEL. DISGLICEMIAS EM USO DE CORTICOIDE.", intercorrencias: "SEM INTERCORRÊNCIAS.", pendencias: "MONITORIZAÇÃO GLICÊMICA E AJUSTE INSULINA.", alertas: ["DISGLICEMIA"] },
  ];
}
