/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TipoRouteImport } from './routes/tipo'
import { Route as RoundRouteImport } from './routes/round'
import { Route as RevisarExtracaoRouteImport } from './routes/revisar-extracao'
import { Route as PacienteInternadoRouteImport } from './routes/paciente-internado'
import { Route as NovoPacienteRouteImport } from './routes/novo-paciente'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AdmissaoNovaRouteImport } from './routes/admissao-nova'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProcessandoJobIdRouteImport } from './routes/processando.$jobId'
import { Route as EvolucaoIdRouteImport } from './routes/evolucao.$id'

const TipoRoute = TipoRouteImport.update({
  id: '/tipo',
  path: '/tipo',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundRoute = RoundRouteImport.update({
  id: '/round',
  path: '/round',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisarExtracaoRoute = RevisarExtracaoRouteImport.update({
  id: '/revisar-extracao',
  path: '/revisar-extracao',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteInternadoRoute = PacienteInternadoRouteImport.update({
  id: '/paciente-internado',
  path: '/paciente-internado',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoPacienteRoute = NovoPacienteRouteImport.update({
  id: '/novo-paciente',
  path: '/novo-paciente',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissaoNovaRoute = AdmissaoNovaRouteImport.update({
  id: '/admissao-nova',
  path: '/admissao-nova',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessandoJobIdRoute = ProcessandoJobIdRouteImport.update({
  id: '/processando/$jobId',
  path: '/processando/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucaoIdRoute = EvolucaoIdRouteImport.update({
  id: '/evolucao/$id',
  path: '/evolucao/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissao-nova': typeof AdmissaoNovaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/novo-paciente': typeof NovoPacienteRoute
  '/paciente-internado': typeof PacienteInternadoRoute
  '/revisar-extracao': typeof RevisarExtracaoRoute
  '/round': typeof RoundRoute
  '/tipo': typeof TipoRoute
  '/evolucao/$id': typeof EvolucaoIdRoute
  '/processando/$jobId': typeof ProcessandoJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissao-nova': typeof AdmissaoNovaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/novo-paciente': typeof NovoPacienteRoute
  '/paciente-internado': typeof PacienteInternadoRoute
  '/revisar-extracao': typeof RevisarExtracaoRoute
  '/round': typeof RoundRoute
  '/tipo': typeof TipoRoute
  '/evolucao/$id': typeof EvolucaoIdRoute
  '/processando/$jobId': typeof ProcessandoJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admissao-nova': typeof AdmissaoNovaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/novo-paciente': typeof NovoPacienteRoute
  '/paciente-internado': typeof PacienteInternadoRoute
  '/revisar-extracao': typeof RevisarExtracaoRoute
  '/round': typeof RoundRoute
  '/tipo': typeof TipoRoute
  '/evolucao/$id': typeof EvolucaoIdRoute
  '/processando/$jobId': typeof ProcessandoJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admissao-nova'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/novo-paciente'
    | '/paciente-internado'
    | '/revisar-extracao'
    | '/round'
    | '/tipo'
    | '/evolucao/$id'
    | '/processando/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admissao-nova'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/novo-paciente'
    | '/paciente-internado'
    | '/revisar-extracao'
    | '/round'
    | '/tipo'
    | '/evolucao/$id'
    | '/processando/$jobId'
  id:
    | '__root__'
    | '/'
    | '/admissao-nova'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/novo-paciente'
    | '/paciente-internado'
    | '/revisar-extracao'
    | '/round'
    | '/tipo'
    | '/evolucao/$id'
    | '/processando/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissaoNovaRoute: typeof AdmissaoNovaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NovoPacienteRoute: typeof NovoPacienteRoute
  PacienteInternadoRoute: typeof PacienteInternadoRoute
  RevisarExtracaoRoute: typeof RevisarExtracaoRoute
  RoundRoute: typeof RoundRoute
  TipoRoute: typeof TipoRoute
  EvolucaoIdRoute: typeof EvolucaoIdRoute
  ProcessandoJobIdRoute: typeof ProcessandoJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tipo': {
      id: '/tipo'
      path: '/tipo'
      fullPath: '/tipo'
      preLoaderRoute: typeof TipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/round': {
      id: '/round'
      path: '/round'
      fullPath: '/round'
      preLoaderRoute: typeof RoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisar-extracao': {
      id: '/revisar-extracao'
      path: '/revisar-extracao'
      fullPath: '/revisar-extracao'
      preLoaderRoute: typeof RevisarExtracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente-internado': {
      id: '/paciente-internado'
      path: '/paciente-internado'
      fullPath: '/paciente-internado'
      preLoaderRoute: typeof PacienteInternadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-paciente': {
      id: '/novo-paciente'
      path: '/novo-paciente'
      fullPath: '/novo-paciente'
      preLoaderRoute: typeof NovoPacienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissao-nova': {
      id: '/admissao-nova'
      path: '/admissao-nova'
      fullPath: '/admissao-nova'
      preLoaderRoute: typeof AdmissaoNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processando/$jobId': {
      id: '/processando/$jobId'
      path: '/processando/$jobId'
      fullPath: '/processando/$jobId'
      preLoaderRoute: typeof ProcessandoJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucao/$id': {
      id: '/evolucao/$id'
      path: '/evolucao/$id'
      fullPath: '/evolucao/$id'
      preLoaderRoute: typeof EvolucaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissaoNovaRoute: AdmissaoNovaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NovoPacienteRoute: NovoPacienteRoute,
  PacienteInternadoRoute: PacienteInternadoRoute,
  RevisarExtracaoRoute: RevisarExtracaoRoute,
  RoundRoute: RoundRoute,
  TipoRoute: TipoRoute,
  EvolucaoIdRoute: EvolucaoIdRoute,
  ProcessandoJobIdRoute: ProcessandoJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
