/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadIaRouteImport } from './routes/upload-ia'
import { Route as TipoRouteImport } from './routes/tipo'
import { Route as TestThrowRouteImport } from './routes/test-throw'
import { Route as RoundRouteImport } from './routes/round'
import { Route as RevisarExtracaoRouteImport } from './routes/revisar-extracao'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PlantoesRouteImport } from './routes/plantoes'
import { Route as PassagemRouteImport } from './routes/passagem'
import { Route as PacienteInternadoRouteImport } from './routes/paciente-internado'
import { Route as NovoPacienteRouteImport } from './routes/novo-paciente'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabRapidoRouteImport } from './routes/lab-rapido'
import { Route as IniciarPlantaoRouteImport } from './routes/iniciar-plantao'
import { Route as EspecialistasRouteImport } from './routes/especialistas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CadastroManualRouteImport } from './routes/cadastro-manual'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdmissaoNovaRouteImport } from './routes/admissao-nova'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProcessandoJobIdRouteImport } from './routes/processando.$jobId'
import { Route as PrescricaoIdRouteImport } from './routes/prescricao.$id'
import { Route as PassagemMassaBulkJobIdRouteImport } from './routes/passagem-massa.$bulkJobId'
import { Route as PacienteTempRouteImport } from './routes/paciente.temp'
import { Route as PacienteIdRouteImport } from './routes/paciente.$id'
import { Route as EspecialistasIdRouteImport } from './routes/especialistas.$id'
import { Route as EncaminhamentoIdRouteImport } from './routes/encaminhamento.$id'
import { Route as EvolucaoIdRouteRouteImport } from './routes/evolucao.$id.route'
import { Route as EvolucaoIdIndexRouteImport } from './routes/evolucao.$id.index'
import { Route as EvolucaoIdHistoricoRouteImport } from './routes/evolucao.$id.historico'

const UploadIaRoute = UploadIaRouteImport.update({
  id: '/upload-ia',
  path: '/upload-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const TipoRoute = TipoRouteImport.update({
  id: '/tipo',
  path: '/tipo',
  getParentRoute: () => rootRouteImport,
} as any)
const TestThrowRoute = TestThrowRouteImport.update({
  id: '/test-throw',
  path: '/test-throw',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundRoute = RoundRouteImport.update({
  id: '/round',
  path: '/round',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisarExtracaoRoute = RevisarExtracaoRouteImport.update({
  id: '/revisar-extracao',
  path: '/revisar-extracao',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantoesRoute = PlantoesRouteImport.update({
  id: '/plantoes',
  path: '/plantoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PassagemRoute = PassagemRouteImport.update({
  id: '/passagem',
  path: '/passagem',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteInternadoRoute = PacienteInternadoRouteImport.update({
  id: '/paciente-internado',
  path: '/paciente-internado',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoPacienteRoute = NovoPacienteRouteImport.update({
  id: '/novo-paciente',
  path: '/novo-paciente',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRapidoRoute = LabRapidoRouteImport.update({
  id: '/lab-rapido',
  path: '/lab-rapido',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciarPlantaoRoute = IniciarPlantaoRouteImport.update({
  id: '/iniciar-plantao',
  path: '/iniciar-plantao',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialistasRoute = EspecialistasRouteImport.update({
  id: '/especialistas',
  path: '/especialistas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroManualRoute = CadastroManualRouteImport.update({
  id: '/cadastro-manual',
  path: '/cadastro-manual',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissaoNovaRoute = AdmissaoNovaRouteImport.update({
  id: '/admissao-nova',
  path: '/admissao-nova',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessandoJobIdRoute = ProcessandoJobIdRouteImport.update({
  id: '/processando/$jobId',
  path: '/processando/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescricaoIdRoute = PrescricaoIdRouteImport.update({
  id: '/prescricao/$id',
  path: '/prescricao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PassagemMassaBulkJobIdRoute = PassagemMassaBulkJobIdRouteImport.update({
  id: '/passagem-massa/$bulkJobId',
  path: '/passagem-massa/$bulkJobId',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteTempRoute = PacienteTempRouteImport.update({
  id: '/paciente/temp',
  path: '/paciente/temp',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteIdRoute = PacienteIdRouteImport.update({
  id: '/paciente/$id',
  path: '/paciente/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialistasIdRoute = EspecialistasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EspecialistasRoute,
} as any)
const EncaminhamentoIdRoute = EncaminhamentoIdRouteImport.update({
  id: '/encaminhamento/$id',
  path: '/encaminhamento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucaoIdRouteRoute = EvolucaoIdRouteRouteImport.update({
  id: '/evolucao/$id',
  path: '/evolucao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucaoIdIndexRoute = EvolucaoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EvolucaoIdRouteRoute,
} as any)
const EvolucaoIdHistoricoRoute = EvolucaoIdHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => EvolucaoIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissao-nova': typeof AdmissaoNovaRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-manual': typeof CadastroManualRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/especialistas': typeof EspecialistasRouteWithChildren
  '/iniciar-plantao': typeof IniciarPlantaoRoute
  '/lab-rapido': typeof LabRapidoRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/novo-paciente': typeof NovoPacienteRoute
  '/paciente-internado': typeof PacienteInternadoRoute
  '/passagem': typeof PassagemRoute
  '/plantoes': typeof PlantoesRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/revisar-extracao': typeof RevisarExtracaoRoute
  '/round': typeof RoundRoute
  '/test-throw': typeof TestThrowRoute
  '/tipo': typeof TipoRoute
  '/upload-ia': typeof UploadIaRoute
  '/evolucao/$id': typeof EvolucaoIdRouteRouteWithChildren
  '/encaminhamento/$id': typeof EncaminhamentoIdRoute
  '/especialistas/$id': typeof EspecialistasIdRoute
  '/paciente/$id': typeof PacienteIdRoute
  '/paciente/temp': typeof PacienteTempRoute
  '/passagem-massa/$bulkJobId': typeof PassagemMassaBulkJobIdRoute
  '/prescricao/$id': typeof PrescricaoIdRoute
  '/processando/$jobId': typeof ProcessandoJobIdRoute
  '/evolucao/$id/historico': typeof EvolucaoIdHistoricoRoute
  '/evolucao/$id/': typeof EvolucaoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissao-nova': typeof AdmissaoNovaRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-manual': typeof CadastroManualRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/especialistas': typeof EspecialistasRouteWithChildren
  '/iniciar-plantao': typeof IniciarPlantaoRoute
  '/lab-rapido': typeof LabRapidoRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/novo-paciente': typeof NovoPacienteRoute
  '/paciente-internado': typeof PacienteInternadoRoute
  '/passagem': typeof PassagemRoute
  '/plantoes': typeof PlantoesRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/revisar-extracao': typeof RevisarExtracaoRoute
  '/round': typeof RoundRoute
  '/test-throw': typeof TestThrowRoute
  '/tipo': typeof TipoRoute
  '/upload-ia': typeof UploadIaRoute
  '/encaminhamento/$id': typeof EncaminhamentoIdRoute
  '/especialistas/$id': typeof EspecialistasIdRoute
  '/paciente/$id': typeof PacienteIdRoute
  '/paciente/temp': typeof PacienteTempRoute
  '/passagem-massa/$bulkJobId': typeof PassagemMassaBulkJobIdRoute
  '/prescricao/$id': typeof PrescricaoIdRoute
  '/processando/$jobId': typeof ProcessandoJobIdRoute
  '/evolucao/$id/historico': typeof EvolucaoIdHistoricoRoute
  '/evolucao/$id': typeof EvolucaoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admissao-nova': typeof AdmissaoNovaRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-manual': typeof CadastroManualRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/especialistas': typeof EspecialistasRouteWithChildren
  '/iniciar-plantao': typeof IniciarPlantaoRoute
  '/lab-rapido': typeof LabRapidoRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/novo-paciente': typeof NovoPacienteRoute
  '/paciente-internado': typeof PacienteInternadoRoute
  '/passagem': typeof PassagemRoute
  '/plantoes': typeof PlantoesRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/revisar-extracao': typeof RevisarExtracaoRoute
  '/round': typeof RoundRoute
  '/test-throw': typeof TestThrowRoute
  '/tipo': typeof TipoRoute
  '/upload-ia': typeof UploadIaRoute
  '/evolucao/$id': typeof EvolucaoIdRouteRouteWithChildren
  '/encaminhamento/$id': typeof EncaminhamentoIdRoute
  '/especialistas/$id': typeof EspecialistasIdRoute
  '/paciente/$id': typeof PacienteIdRoute
  '/paciente/temp': typeof PacienteTempRoute
  '/passagem-massa/$bulkJobId': typeof PassagemMassaBulkJobIdRoute
  '/prescricao/$id': typeof PrescricaoIdRoute
  '/processando/$jobId': typeof ProcessandoJobIdRoute
  '/evolucao/$id/historico': typeof EvolucaoIdHistoricoRoute
  '/evolucao/$id/': typeof EvolucaoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admissao-nova'
    | '/cadastro'
    | '/cadastro-manual'
    | '/configuracoes'
    | '/dashboard'
    | '/especialistas'
    | '/iniciar-plantao'
    | '/lab-rapido'
    | '/login'
    | '/nova-senha'
    | '/novo-paciente'
    | '/paciente-internado'
    | '/passagem'
    | '/plantoes'
    | '/recuperar-senha'
    | '/revisar-extracao'
    | '/round'
    | '/test-throw'
    | '/tipo'
    | '/upload-ia'
    | '/evolucao/$id'
    | '/encaminhamento/$id'
    | '/especialistas/$id'
    | '/paciente/$id'
    | '/paciente/temp'
    | '/passagem-massa/$bulkJobId'
    | '/prescricao/$id'
    | '/processando/$jobId'
    | '/evolucao/$id/historico'
    | '/evolucao/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admissao-nova'
    | '/cadastro'
    | '/cadastro-manual'
    | '/configuracoes'
    | '/dashboard'
    | '/especialistas'
    | '/iniciar-plantao'
    | '/lab-rapido'
    | '/login'
    | '/nova-senha'
    | '/novo-paciente'
    | '/paciente-internado'
    | '/passagem'
    | '/plantoes'
    | '/recuperar-senha'
    | '/revisar-extracao'
    | '/round'
    | '/test-throw'
    | '/tipo'
    | '/upload-ia'
    | '/encaminhamento/$id'
    | '/especialistas/$id'
    | '/paciente/$id'
    | '/paciente/temp'
    | '/passagem-massa/$bulkJobId'
    | '/prescricao/$id'
    | '/processando/$jobId'
    | '/evolucao/$id/historico'
    | '/evolucao/$id'
  id:
    | '__root__'
    | '/'
    | '/admissao-nova'
    | '/cadastro'
    | '/cadastro-manual'
    | '/configuracoes'
    | '/dashboard'
    | '/especialistas'
    | '/iniciar-plantao'
    | '/lab-rapido'
    | '/login'
    | '/nova-senha'
    | '/novo-paciente'
    | '/paciente-internado'
    | '/passagem'
    | '/plantoes'
    | '/recuperar-senha'
    | '/revisar-extracao'
    | '/round'
    | '/test-throw'
    | '/tipo'
    | '/upload-ia'
    | '/evolucao/$id'
    | '/encaminhamento/$id'
    | '/especialistas/$id'
    | '/paciente/$id'
    | '/paciente/temp'
    | '/passagem-massa/$bulkJobId'
    | '/prescricao/$id'
    | '/processando/$jobId'
    | '/evolucao/$id/historico'
    | '/evolucao/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissaoNovaRoute: typeof AdmissaoNovaRoute
  CadastroRoute: typeof CadastroRoute
  CadastroManualRoute: typeof CadastroManualRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  EspecialistasRoute: typeof EspecialistasRouteWithChildren
  IniciarPlantaoRoute: typeof IniciarPlantaoRoute
  LabRapidoRoute: typeof LabRapidoRoute
  LoginRoute: typeof LoginRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
  NovoPacienteRoute: typeof NovoPacienteRoute
  PacienteInternadoRoute: typeof PacienteInternadoRoute
  PassagemRoute: typeof PassagemRoute
  PlantoesRoute: typeof PlantoesRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RevisarExtracaoRoute: typeof RevisarExtracaoRoute
  RoundRoute: typeof RoundRoute
  TestThrowRoute: typeof TestThrowRoute
  TipoRoute: typeof TipoRoute
  UploadIaRoute: typeof UploadIaRoute
  EvolucaoIdRouteRoute: typeof EvolucaoIdRouteRouteWithChildren
  EncaminhamentoIdRoute: typeof EncaminhamentoIdRoute
  PacienteIdRoute: typeof PacienteIdRoute
  PacienteTempRoute: typeof PacienteTempRoute
  PassagemMassaBulkJobIdRoute: typeof PassagemMassaBulkJobIdRoute
  PrescricaoIdRoute: typeof PrescricaoIdRoute
  ProcessandoJobIdRoute: typeof ProcessandoJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload-ia': {
      id: '/upload-ia'
      path: '/upload-ia'
      fullPath: '/upload-ia'
      preLoaderRoute: typeof UploadIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tipo': {
      id: '/tipo'
      path: '/tipo'
      fullPath: '/tipo'
      preLoaderRoute: typeof TipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-throw': {
      id: '/test-throw'
      path: '/test-throw'
      fullPath: '/test-throw'
      preLoaderRoute: typeof TestThrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/round': {
      id: '/round'
      path: '/round'
      fullPath: '/round'
      preLoaderRoute: typeof RoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisar-extracao': {
      id: '/revisar-extracao'
      path: '/revisar-extracao'
      fullPath: '/revisar-extracao'
      preLoaderRoute: typeof RevisarExtracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantoes': {
      id: '/plantoes'
      path: '/plantoes'
      fullPath: '/plantoes'
      preLoaderRoute: typeof PlantoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passagem': {
      id: '/passagem'
      path: '/passagem'
      fullPath: '/passagem'
      preLoaderRoute: typeof PassagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente-internado': {
      id: '/paciente-internado'
      path: '/paciente-internado'
      fullPath: '/paciente-internado'
      preLoaderRoute: typeof PacienteInternadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-paciente': {
      id: '/novo-paciente'
      path: '/novo-paciente'
      fullPath: '/novo-paciente'
      preLoaderRoute: typeof NovoPacienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-rapido': {
      id: '/lab-rapido'
      path: '/lab-rapido'
      fullPath: '/lab-rapido'
      preLoaderRoute: typeof LabRapidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciar-plantao': {
      id: '/iniciar-plantao'
      path: '/iniciar-plantao'
      fullPath: '/iniciar-plantao'
      preLoaderRoute: typeof IniciarPlantaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialistas': {
      id: '/especialistas'
      path: '/especialistas'
      fullPath: '/especialistas'
      preLoaderRoute: typeof EspecialistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-manual': {
      id: '/cadastro-manual'
      path: '/cadastro-manual'
      fullPath: '/cadastro-manual'
      preLoaderRoute: typeof CadastroManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissao-nova': {
      id: '/admissao-nova'
      path: '/admissao-nova'
      fullPath: '/admissao-nova'
      preLoaderRoute: typeof AdmissaoNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processando/$jobId': {
      id: '/processando/$jobId'
      path: '/processando/$jobId'
      fullPath: '/processando/$jobId'
      preLoaderRoute: typeof ProcessandoJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescricao/$id': {
      id: '/prescricao/$id'
      path: '/prescricao/$id'
      fullPath: '/prescricao/$id'
      preLoaderRoute: typeof PrescricaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passagem-massa/$bulkJobId': {
      id: '/passagem-massa/$bulkJobId'
      path: '/passagem-massa/$bulkJobId'
      fullPath: '/passagem-massa/$bulkJobId'
      preLoaderRoute: typeof PassagemMassaBulkJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente/temp': {
      id: '/paciente/temp'
      path: '/paciente/temp'
      fullPath: '/paciente/temp'
      preLoaderRoute: typeof PacienteTempRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente/$id': {
      id: '/paciente/$id'
      path: '/paciente/$id'
      fullPath: '/paciente/$id'
      preLoaderRoute: typeof PacienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialistas/$id': {
      id: '/especialistas/$id'
      path: '/$id'
      fullPath: '/especialistas/$id'
      preLoaderRoute: typeof EspecialistasIdRouteImport
      parentRoute: typeof EspecialistasRoute
    }
    '/encaminhamento/$id': {
      id: '/encaminhamento/$id'
      path: '/encaminhamento/$id'
      fullPath: '/encaminhamento/$id'
      preLoaderRoute: typeof EncaminhamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucao/$id': {
      id: '/evolucao/$id'
      path: '/evolucao/$id'
      fullPath: '/evolucao/$id'
      preLoaderRoute: typeof EvolucaoIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucao/$id/': {
      id: '/evolucao/$id/'
      path: '/'
      fullPath: '/evolucao/$id/'
      preLoaderRoute: typeof EvolucaoIdIndexRouteImport
      parentRoute: typeof EvolucaoIdRouteRoute
    }
    '/evolucao/$id/historico': {
      id: '/evolucao/$id/historico'
      path: '/historico'
      fullPath: '/evolucao/$id/historico'
      preLoaderRoute: typeof EvolucaoIdHistoricoRouteImport
      parentRoute: typeof EvolucaoIdRouteRoute
    }
  }
}

interface EspecialistasRouteChildren {
  EspecialistasIdRoute: typeof EspecialistasIdRoute
}

const EspecialistasRouteChildren: EspecialistasRouteChildren = {
  EspecialistasIdRoute: EspecialistasIdRoute,
}

const EspecialistasRouteWithChildren = EspecialistasRoute._addFileChildren(
  EspecialistasRouteChildren,
)

interface EvolucaoIdRouteRouteChildren {
  EvolucaoIdHistoricoRoute: typeof EvolucaoIdHistoricoRoute
  EvolucaoIdIndexRoute: typeof EvolucaoIdIndexRoute
}

const EvolucaoIdRouteRouteChildren: EvolucaoIdRouteRouteChildren = {
  EvolucaoIdHistoricoRoute: EvolucaoIdHistoricoRoute,
  EvolucaoIdIndexRoute: EvolucaoIdIndexRoute,
}

const EvolucaoIdRouteRouteWithChildren = EvolucaoIdRouteRoute._addFileChildren(
  EvolucaoIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissaoNovaRoute: AdmissaoNovaRoute,
  CadastroRoute: CadastroRoute,
  CadastroManualRoute: CadastroManualRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  EspecialistasRoute: EspecialistasRouteWithChildren,
  IniciarPlantaoRoute: IniciarPlantaoRoute,
  LabRapidoRoute: LabRapidoRoute,
  LoginRoute: LoginRoute,
  NovaSenhaRoute: NovaSenhaRoute,
  NovoPacienteRoute: NovoPacienteRoute,
  PacienteInternadoRoute: PacienteInternadoRoute,
  PassagemRoute: PassagemRoute,
  PlantoesRoute: PlantoesRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RevisarExtracaoRoute: RevisarExtracaoRoute,
  RoundRoute: RoundRoute,
  TestThrowRoute: TestThrowRoute,
  TipoRoute: TipoRoute,
  UploadIaRoute: UploadIaRoute,
  EvolucaoIdRouteRoute: EvolucaoIdRouteRouteWithChildren,
  EncaminhamentoIdRoute: EncaminhamentoIdRoute,
  PacienteIdRoute: PacienteIdRoute,
  PacienteTempRoute: PacienteTempRoute,
  PassagemMassaBulkJobIdRoute: PassagemMassaBulkJobIdRoute,
  PrescricaoIdRoute: PrescricaoIdRoute,
  ProcessandoJobIdRoute: ProcessandoJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
